M48
; DRILL file KiCad 10.0.0 date 2026-10-03T00:36:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-03T00:36:15-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X51.993Y-70.0
X51.993Y-80.0
X54.493Y-70.0
X54.493Y-80.0
X59.493Y-75.0
T2
X55.0Y-55.0
X55.0Y-95.0
X95.0Y-55.0
X95.0Y-95.0
M30
